# Generated by Django 3.0.7 on 2023-02-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JmlLulusanPesertaPelatihan',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('kode_provinsi', models.IntegerField(blank=True, null=True)),
                ('nama_provinsi', models.CharField(blank=True, max_length=255, null=True)),
                ('nama_bidang', models.CharField(blank=True, max_length=255, null=True)),
                ('nama_kegiatan', models.CharField(blank=True, max_length=255, null=True)),
                ('jumlah_lulusan', models.BigIntegerField(blank=True, null=True)),
                ('satuan', models.CharField(blank=True, max_length=30, null=True)),
                ('tahun', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JmlPegawaiPppk',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('kode_provinsi', models.IntegerField(blank=True, null=True)),
                ('nama_provinsi', models.CharField(blank=True, max_length=255, null=True)),
                ('perangkat_daerah', models.CharField(blank=True, max_length=255, null=True)),
                ('tingkat_pendidikan', models.CharField(blank=True, max_length=30, null=True)),
                ('jumlah_pppk', models.BigIntegerField(blank=True, null=True)),
                ('satuan', models.CharField(blank=True, max_length=30, null=True)),
                ('tahun', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JmlPengeluaranKerbau',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('kode_provinsi', models.IntegerField(blank=True, null=True)),
                ('nama_provinsi', models.CharField(blank=True, max_length=255, null=True)),
                ('kode_kabupaten_kota', models.IntegerField(blank=True, null=True)),
                ('nama_kabupaten_kota', models.CharField(blank=True, max_length=255, null=True)),
                ('kategori_pengeluaran', models.CharField(blank=True, max_length=100, null=True)),
                ('jumlah_pengeluaran', models.BigIntegerField(blank=True, null=True)),
                ('satuan', models.CharField(blank=True, max_length=30, null=True)),
                ('tahun', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
